# Generated by Django 2.2.16 on 2020-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='dfgwrgtw',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
